package com.etf.crm.enums;

public enum ContractStatus {
    CREATED,
    FINALIZED,
    CONTRACT_SIGNED,
    SALESMAN_CLOSED,
    CLOSED_BY_SYSTEM,
    CONTRACT_SIGNED_AND_VERIFIED,
    CONTRACT_SIGNED_AND_REJECTED,
}
