package com.etf.crm.enums;

public enum OfferStatus {
    DRAFT,
    WHAT_IF_ANALYSIS,
    L1_PENDING,
    L2_PENDING,
    L3_PENDING,
    SALESMEN_CLOSED,
    CLOSED_BY_SYSTEM,
    L1_REJECTED,
    L2_REJECTED,
    L3_REJECTED,
    CUSTOMER_PENDING,
    CUSTOMER_ACCEPTED,
    CONCLUDED
}
